// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually — run `bun run generate-models` to update.
//
// Source: https://models.dev/api.json (provider "nan"), fetched 2026-10-02T16:03:10.971Z
// Provenance: every contextWindow/maxTokens/input/cost value traces to
// models.dev or to the per-entry notes below. Nothing is invented; entries
// models.dev documents incompletely are omitted and flagged instead.
//
// NaN serves these via LiteLLM behind an OpenAI-compatible API; pricing is
// membership-quota based, which models.dev reports as zero per-token cost.

import type { GeneratedModelEntry } from "../src/fetch-models.ts";

export const NAN_GENERATED_MODELS: readonly GeneratedModelEntry[] = [
	{
		"id": "deepseek-v4-flash",
		"name": "DeepSeek V4.1 Flash",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 1000000,
		"maxTokens": 32768,
		"reasoningEffortValues": [
			"none"
		],
		"thinkingLevelMap": {
			"off": "none"
		},
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"supportsFinishReason": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested. supportsFinishReason true (2026-09-13, issue #2): the LiteLLM gateway intermittently closes SSE streams before emitting finish_reason; with true pi-ai raises 'Stream ended without finish_reason', which matches pi-ai's retryable-provider pattern ('ended without') and is retried automatically, whereas false silently synthesized stop/toolUse and stalled the turn mid-answer. supportsUsageInStreaming true (2026-09-16, issue #7): NaN's published schema is silent about stream_options, but the live gateway honors it — two identical streaming calls per model, differing only in stream_options: { include_usage: true }, returned 0 usage chunks without it and exactly 1 with it (prompt/completion/reasoning/cached token counts) on deepseek-v4-flash, glm5.3-flash, qwen3.6, mimo-v2.5 and gemma4, and a real pi session then recorded token counts where it recorded zeros. pi-ai only sends stream_options when this is not false, and the sanitizer forwards it when the model declares true, so chat models opt in by default and usage is reported (issue #4). A model that does not report streaming usage can still opt out per model with a models.json compat override (supportsUsageInStreaming: false); the sanitizer then strips stream_options and the payload stays strict.",
			"input includes image: NaN serves the Vision-Exp variant ('takes images as input', https://nan.builders/docs/models; the image_url content-parts in https://nan.builders/openapi.json list deepseek-v4-flash among the vision models). models.dev provider nan also lists text+image now (DeepSeek V4.1 Flash entry, checked 2026-09-13; its 2026-09-07 snapshot listed text only), so this override is kept as a pin for the vision capability rather than as a divergence. maxTokens 32768 per the official NaN pi docs (https://nan.builders/docs/pi, 'the same set the NaN CLI writes', checked 2026-10-02) closing issue #20 — the gateway now rejects max_tokens above ~256k for this model with 403 permission_error (measured 2026-10-02: 256,000 → 200; 262,143 → 403), and the previous models.dev-derived 384000 made every pi request fail since pi-ai sends max_tokens = model.maxTokens when no cap is set. models.dev still lists 384000, so this override pins the documented value. reasoning_effort_values=[\"none\"] (issue #16, measured 2026-09-27 against live gateway, repro included in the issue): only \"none\" deterministically disables reasoning (0 reasoning tokens, answer produced). Every other value leaves 13-14K reasoning tokens and causes runaway reasoning (finish_reason:\"length\" with ZERO answer text). The catalog declares only [\"none\"] because the remaining values are useless noise. thinkingLevelMap { off: \"none\" } (issue #16, measured 2026-09-27): when pi maps reasoning:\"off\" to reasoningEffort:undefined, the thinkingLevelMap.off=\"none\" supplies the effort so the gateway receives reasoning_effort:\"none\" and does NOT enter runaway reasoning mode."
		],
		"extras": {
			"id": "deepseek-v4-flash",
			"name": "DeepSeek V4.1 Flash",
			"description": "DeepSeek V4.1 Flash model for reasoning and agentic coding",
			"family": "deepseek-flash",
			"attachment": true,
			"reasoning": true,
			"reasoning_options": [],
			"tool_call": true,
			"structured_output": true,
			"temperature": true,
			"knowledge": "2025-05",
			"release_date": "2026-09-10",
			"last_updated": "2026-09-10",
			"modalities": {
				"input": [
					"text",
					"image"
				],
				"output": [
					"text"
				]
			},
			"open_weights": true,
			"limit": {
				"context": 1000000,
				"output": 384000
			},
			"cost": {
				"input": 0,
				"output": 0
			},
			"canonical_model_id": "deepseek/deepseek-v4.1-flash"
		}
	},
	{
		"id": "gemma4",
		"name": "Gemma 4 26B A4B IT",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 262144,
		"maxTokens": 32768,
		"reasoningEffortValues": [
			"none",
			"minimal",
			"low",
			"medium",
			"high",
			"max"
		],
		"thinkingLevelMap": {
			"off": "none"
		},
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"supportsFinishReason": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested. supportsFinishReason true (2026-09-13, issue #2): the LiteLLM gateway intermittently closes SSE streams before emitting finish_reason; with true pi-ai raises 'Stream ended without finish_reason', which matches pi-ai's retryable-provider pattern ('ended without') and is retried automatically, whereas false silently synthesized stop/toolUse and stalled the turn mid-answer. supportsUsageInStreaming true (2026-09-16, issue #7): NaN's published schema is silent about stream_options, but the live gateway honors it — two identical streaming calls per model, differing only in stream_options: { include_usage: true }, returned 0 usage chunks without it and exactly 1 with it (prompt/completion/reasoning/cached token counts) on deepseek-v4-flash, glm5.3-flash, qwen3.6, mimo-v2.5 and gemma4, and a real pi session then recorded token counts where it recorded zeros. pi-ai only sends stream_options when this is not false, and the sanitizer forwards it when the model declares true, so chat models opt in by default and usage is reported (issue #4). A model that does not report streaming usage can still opt out per model with a models.json compat override (supportsUsageInStreaming: false); the sanitizer then strips stream_options and the payload stays strict.",
			"thinkingLevelMap { off: \"none\" } (issue #16): NaN docs state that with no reasoning_effort parameter gemma4 defaults to reasoning ON (16,384-token budget), while `none`/`minimal` skip reasoning entirely (https://nan.builders/docs/models#controlling-reasoning, checked 2026-10-01). pi maps reasoning:\"off\" to reasoningEffort:undefined, so without this map `thinking: off` sent no parameter and the model reasoned anyway; the map sends reasoning_effort:\"none\" and actually disables reasoning."
		],
		"extras": {
			"id": "gemma4",
			"name": "Gemma 4 26B A4B IT",
			"description": "Open Gemma instruction model for efficient chat and self-hosted deployments",
			"family": "gemma",
			"attachment": true,
			"reasoning": true,
			"reasoning_options": [
				{
					"type": "effort",
					"values": [
						"none",
						"low",
						"medium",
						"high",
						"max"
					]
				}
			],
			"tool_call": true,
			"structured_output": true,
			"temperature": true,
			"release_date": "2026-04-02",
			"last_updated": "2026-04-02",
			"modalities": {
				"input": [
					"text",
					"image"
				],
				"output": [
					"text"
				]
			},
			"open_weights": true,
			"limit": {
				"context": 262144,
				"output": 32768
			},
			"cost": {
				"input": 0,
				"output": 0
			},
			"canonical_model_id": "google/gemma-4-26b-a4b-it"
		}
	},
	{
		"id": "glm5.3-flash",
		"name": "GLM-5.3-Flash",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 1000000,
		"maxTokens": 131072,
		"reasoningEffortValues": [
			"minimal",
			"low",
			"medium",
			"high",
			"max"
		],
		"thinkingLevelMap": {
			"off": "minimal"
		},
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"supportsFinishReason": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested. supportsFinishReason true (2026-09-13, issue #2): the LiteLLM gateway intermittently closes SSE streams before emitting finish_reason; with true pi-ai raises 'Stream ended without finish_reason', which matches pi-ai's retryable-provider pattern ('ended without') and is retried automatically, whereas false silently synthesized stop/toolUse and stalled the turn mid-answer. supportsUsageInStreaming true (2026-09-16, issue #7): NaN's published schema is silent about stream_options, but the live gateway honors it — two identical streaming calls per model, differing only in stream_options: { include_usage: true }, returned 0 usage chunks without it and exactly 1 with it (prompt/completion/reasoning/cached token counts) on deepseek-v4-flash, glm5.3-flash, qwen3.6, mimo-v2.5 and gemma4, and a real pi session then recorded token counts where it recorded zeros. pi-ai only sends stream_options when this is not false, and the sanitizer forwards it when the model declares true, so chat models opt in by default and usage is reported (issue #4). A model that does not report streaming usage can still opt out per model with a models.json compat override (supportsUsageInStreaming: false); the sanitizer then strips stream_options and the payload stays strict.",
			"thinkingLevelMap { off: \"minimal\" } (issue #16, measured 2026-09-27 against live gateway, repro included in the issue): when pi maps reasoning:\"off\" to reasoningEffort:undefined, the thinkingLevelMap.off=\"minimal\" supplies the effort so the gateway receives reasoning_effort:\"minimal\" (38 reasoning tokens + answer). Note: \"none\" does NOT suppress reasoning on glm5.3-flash (13,382 tokens) — only \"minimal\" was measured to be effective. reasoning_effort_values includes \"minimal\" (not documented by NaN docs but accepted and effective by the gateway, issue #16)."
		],
		"extras": {
			"id": "glm5.3-flash",
			"name": "GLM-5.3-Flash",
			"description": "Native multimodal GLM model for efficient coding and long-horizon agent tasks",
			"family": "glm-flash",
			"attachment": true,
			"reasoning": true,
			"reasoning_options": [
				{
					"type": "effort",
					"values": [
						"low",
						"medium",
						"high",
						"max"
					]
				}
			],
			"tool_call": true,
			"structured_output": true,
			"temperature": true,
			"release_date": "2026-08-26",
			"last_updated": "2026-08-26",
			"modalities": {
				"input": [
					"text",
					"image"
				],
				"output": [
					"text"
				]
			},
			"open_weights": true,
			"limit": {
				"context": 1000000,
				"output": 131072
			},
			"cost": {
				"input": 0,
				"output": 0
			},
			"canonical_model_id": "zhipuai/glm-5.3-flash"
		}
	},
	{
		"id": "mimo-v2.6-flash",
		"name": "MiMo-V2.6-Flash",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 1048576,
		"maxTokens": 131072,
		"reasoningEffortValues": [],
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"supportsFinishReason": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested. supportsFinishReason true (2026-09-13, issue #2): the LiteLLM gateway intermittently closes SSE streams before emitting finish_reason; with true pi-ai raises 'Stream ended without finish_reason', which matches pi-ai's retryable-provider pattern ('ended without') and is retried automatically, whereas false silently synthesized stop/toolUse and stalled the turn mid-answer. supportsUsageInStreaming true (2026-09-16, issue #7): NaN's published schema is silent about stream_options, but the live gateway honors it — two identical streaming calls per model, differing only in stream_options: { include_usage: true }, returned 0 usage chunks without it and exactly 1 with it (prompt/completion/reasoning/cached token counts) on deepseek-v4-flash, glm5.3-flash, qwen3.6, mimo-v2.5 and gemma4, and a real pi session then recorded token counts where it recorded zeros. pi-ai only sends stream_options when this is not false, and the sanitizer forwards it when the model declares true, so chat models opt in by default and usage is reported (issue #4). A model that does not report streaming usage can still opt out per model with a models.json compat override (supportsUsageInStreaming: false); the sanitizer then strips stream_options and the payload stays strict.",
			"manual-only: \"mimo-v2.6-flash\" skipped: models.dev provider \"nan\" now lists it, so the manual-only entry is not emitted and the models.dev values are used (omnimodal model (text, image, audio input) served by NaN; limits and modalities from https://nan.builders/docs/models#mimo-v2-6-flash (checked 2026-09-25, quotas re-checked 2026-09-29): 1,048,576 context / 131,072 max output / 1.0B monthly quota per member. Reasoning: accepted, depth not adjustable (docs table, checked 2026-09-29). Tool calling: yes. Streaming: yes. Input modalities (pi-representable): text, image (audio not representable in pi's Model type). Fallback entry: emitted only while models.dev provider nan does not list the model — models.dev started listing it on 2026-09-29, so the generator then keeps the models.dev values and attaches this note to that entry instead of emitting a second one.)"
		],
		"extras": {
			"id": "mimo-v2.6-flash",
			"name": "MiMo-V2.6-Flash",
			"description": "MiMo Flash model for multimodal coding agents and long-context automation",
			"family": "mimo",
			"attachment": true,
			"reasoning": true,
			"reasoning_options": [],
			"tool_call": true,
			"temperature": true,
			"release_date": "2026-09-22",
			"last_updated": "2026-09-22",
			"modalities": {
				"input": [
					"text",
					"image",
					"audio"
				],
				"output": [
					"text"
				]
			},
			"open_weights": true,
			"limit": {
				"context": 1048576,
				"output": 131072
			},
			"cost": {
				"input": 0,
				"output": 0
			},
			"canonical_model_id": "xiaomi/mimo-v2.6-flash"
		}
	},
	{
		"id": "qwen3.6",
		"name": "Qwen3.6 35B-A3B",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 262144,
		"maxTokens": 65536,
		"reasoningEffortValues": [
			"none",
			"minimal",
			"low",
			"medium",
			"high",
			"max"
		],
		"thinkingLevelMap": {
			"off": "none"
		},
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"supportsFinishReason": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested. supportsFinishReason true (2026-09-13, issue #2): the LiteLLM gateway intermittently closes SSE streams before emitting finish_reason; with true pi-ai raises 'Stream ended without finish_reason', which matches pi-ai's retryable-provider pattern ('ended without') and is retried automatically, whereas false silently synthesized stop/toolUse and stalled the turn mid-answer. supportsUsageInStreaming true (2026-09-16, issue #7): NaN's published schema is silent about stream_options, but the live gateway honors it — two identical streaming calls per model, differing only in stream_options: { include_usage: true }, returned 0 usage chunks without it and exactly 1 with it (prompt/completion/reasoning/cached token counts) on deepseek-v4-flash, glm5.3-flash, qwen3.6, mimo-v2.5 and gemma4, and a real pi session then recorded token counts where it recorded zeros. pi-ai only sends stream_options when this is not false, and the sanitizer forwards it when the model declares true, so chat models opt in by default and usage is reported (issue #4). A model that does not report streaming usage can still opt out per model with a models.json compat override (supportsUsageInStreaming: false); the sanitizer then strips stream_options and the payload stays strict.",
			"thinkingLevelMap { off: \"none\" } (issue #16): NaN docs state that with no reasoning_effort parameter every model uses its own default and that default is reasoning ON for qwen3.6 (16,384-token budget), while `none` and `minimal` skip the reasoning phase entirely (https://nan.builders/docs/models#controlling-reasoning, checked 2026-10-01). pi maps reasoning:\"off\" to reasoningEffort:undefined, so without this map `thinking: off` sent no parameter and the model reasoned anyway; the map sends reasoning_effort:\"none\" and actually disables reasoning."
		],
		"extras": {
			"id": "qwen3.6",
			"name": "Qwen3.6 35B-A3B",
			"description": "Open multimodal Qwen MoE for local agents that need vision, audio, and code",
			"family": "qwen",
			"attachment": true,
			"reasoning": true,
			"reasoning_options": [
				{
					"type": "effort",
					"values": [
						"none",
						"low",
						"medium",
						"high",
						"max"
					]
				}
			],
			"tool_call": true,
			"structured_output": true,
			"temperature": true,
			"release_date": "2026-04-17",
			"last_updated": "2026-04-17",
			"modalities": {
				"input": [
					"text",
					"image"
				],
				"output": [
					"text"
				]
			},
			"open_weights": true,
			"limit": {
				"context": 262144,
				"output": 65536
			},
			"cost": {
				"input": 0,
				"output": 0
			},
			"canonical_model_id": "alibaba/qwen3.6-35b-a3b"
		}
	},
	{
		"id": "qwen3.8-flash",
		"name": "Qwen3.8 Flash",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 262144,
		"maxTokens": 131072,
		"reasoningEffortValues": [],
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"supportsFinishReason": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested. supportsFinishReason true (2026-09-13, issue #2): the LiteLLM gateway intermittently closes SSE streams before emitting finish_reason; with true pi-ai raises 'Stream ended without finish_reason', which matches pi-ai's retryable-provider pattern ('ended without') and is retried automatically, whereas false silently synthesized stop/toolUse and stalled the turn mid-answer. supportsUsageInStreaming true (2026-09-16, issue #7): NaN's published schema is silent about stream_options, but the live gateway honors it — two identical streaming calls per model, differing only in stream_options: { include_usage: true }, returned 0 usage chunks without it and exactly 1 with it (prompt/completion/reasoning/cached token counts) on deepseek-v4-flash, glm5.3-flash, qwen3.6, mimo-v2.5 and gemma4, and a real pi session then recorded token counts where it recorded zeros. pi-ai only sends stream_options when this is not false, and the sanitizer forwards it when the model declares true, so chat models opt in by default and usage is reported (issue #4). A model that does not report streaming usage can still opt out per model with a models.json compat override (supportsUsageInStreaming: false); the sanitizer then strips stream_options and the payload stays strict.",
			"contextWindow 262,144: the earlier 1,000,000 override (maintainer-confirmed 2026-09-05) was withdrawn 2026-09-07 — the updated https://nan.builders/docs/models still states '262K token context, the model's native window' and models.dev agrees at 262,144; NaN docs are treated as the most reliable source (maintainer instruction, 2026-09-07)."
		],
		"extras": {
			"id": "qwen3.8-flash",
			"name": "Qwen3.8 Flash",
			"description": "Qwen vision-language model for visual reasoning, documents, and agent tasks",
			"family": "qwen",
			"attachment": true,
			"reasoning": true,
			"reasoning_options": [],
			"tool_call": true,
			"structured_output": true,
			"release_date": "2026-08-26",
			"last_updated": "2026-08-26",
			"modalities": {
				"input": [
					"text",
					"image"
				],
				"output": [
					"text"
				]
			},
			"open_weights": false,
			"limit": {
				"context": 262144,
				"output": 131072
			},
			"cost": {
				"input": 0,
				"output": 0
			},
			"canonical_model_id": "alibaba/qwen3.8-flash"
		}
	}
];

export const GENERATED_CATALOG_META = {
	source: "https://models.dev/api.json",
	modelsDevProvider: "nan",
	fetchedAt: "2026-10-02T16:03:10.971Z",
	modelCount: 6,
	models: ["deepseek-v4-flash","gemma4","glm5.3-flash","mimo-v2.6-flash","qwen3.6","qwen3.8-flash"],
	notes: [
	"non-chat: \"qwen-image-2.1\" excluded from the chat catalog (image-generation model (text→image; output modality image) documented in https://nan.builders/docs/models and https://nan.builders/openapi.json (checked 2026-09-29) — not a chat model, out of the static chat catalog (models.dev reports limit.output 0))",
	"live-only: \"glm5.3\" kept out of the static catalog (premium-tier model (models.dev now documents it with 1M context / 131,072 max output; NaN docs https://nan.builders/docs/models + https://nan.builders/openapi.json, checked 2026-09-13) kept live-only so a non-premium key never sees a model it cannot call when the live /models fetch is unavailable; premium keys still get it via the /models refresh with conservative placeholder limits)",
	"provider-removed: \"glm5.2\" excluded from the catalog (removed by NaN (2026-09-05); absent from the official chat model list in https://nan.builders/openapi.json and https://nan.builders/docs/models (checked 2026-09-07) while models.dev provider nan still listed it — excluded so regeneration does not resurrect it)",
	"provider-removed: \"mimo-v2.5\" excluded from the catalog (removed by NaN (checked 2026-09-29): zero mentions in https://nan.builders/docs/models and in the model param description of https://nan.builders/openapi.json, and models.dev provider nan dropped it as well — superseded by mimo-v2.6-flash; excluded so regeneration does not resurrect it)",
	"non-chat: \"qwen3-embedding\" excluded from the chat catalog (embedding endpoint (https://nan.builders/docs/models, checked 2026-10-01) — not a chat model)",
	"non-chat: \"rerank\" excluded from the chat catalog (rerank endpoint (https://nan.builders/docs/models, checked 2026-10-01) — not a chat model)",
	"non-chat: \"kokoro\" excluded from the chat catalog (text-to-speech (TTS) endpoint (https://nan.builders/docs/models, checked 2026-10-01) — not a chat model)",
	"non-chat: \"whisper\" excluded from the chat catalog (speech-to-text (STT) endpoint (https://nan.builders/docs/models, checked 2026-10-01) — not a chat model)",
	"non-chat: \"flux-2-klein\" excluded from the chat catalog (image generation endpoint (https://nan.builders/docs/models, checked 2026-10-01) — not a chat model)",
	"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested. supportsFinishReason true (2026-09-13, issue #2): the LiteLLM gateway intermittently closes SSE streams before emitting finish_reason; with true pi-ai raises 'Stream ended without finish_reason', which matches pi-ai's retryable-provider pattern ('ended without') and is retried automatically, whereas false silently synthesized stop/toolUse and stalled the turn mid-answer. supportsUsageInStreaming true (2026-09-16, issue #7): NaN's published schema is silent about stream_options, but the live gateway honors it — two identical streaming calls per model, differing only in stream_options: { include_usage: true }, returned 0 usage chunks without it and exactly 1 with it (prompt/completion/reasoning/cached token counts) on deepseek-v4-flash, glm5.3-flash, qwen3.6, mimo-v2.5 and gemma4, and a real pi session then recorded token counts where it recorded zeros. pi-ai only sends stream_options when this is not false, and the sanitizer forwards it when the model declares true, so chat models opt in by default and usage is reported (issue #4). A model that does not report streaming usage can still opt out per model with a models.json compat override (supportsUsageInStreaming: false); the sanitizer then strips stream_options and the payload stays strict.",
	"input includes image: NaN serves the Vision-Exp variant ('takes images as input', https://nan.builders/docs/models; the image_url content-parts in https://nan.builders/openapi.json list deepseek-v4-flash among the vision models). models.dev provider nan also lists text+image now (DeepSeek V4.1 Flash entry, checked 2026-09-13; its 2026-09-07 snapshot listed text only), so this override is kept as a pin for the vision capability rather than as a divergence. maxTokens 32768 per the official NaN pi docs (https://nan.builders/docs/pi, 'the same set the NaN CLI writes', checked 2026-10-02) closing issue #20 — the gateway now rejects max_tokens above ~256k for this model with 403 permission_error (measured 2026-10-02: 256,000 → 200; 262,143 → 403), and the previous models.dev-derived 384000 made every pi request fail since pi-ai sends max_tokens = model.maxTokens when no cap is set. models.dev still lists 384000, so this override pins the documented value. reasoning_effort_values=[\"none\"] (issue #16, measured 2026-09-27 against live gateway, repro included in the issue): only \"none\" deterministically disables reasoning (0 reasoning tokens, answer produced). Every other value leaves 13-14K reasoning tokens and causes runaway reasoning (finish_reason:\"length\" with ZERO answer text). The catalog declares only [\"none\"] because the remaining values are useless noise. thinkingLevelMap { off: \"none\" } (issue #16, measured 2026-09-27): when pi maps reasoning:\"off\" to reasoningEffort:undefined, the thinkingLevelMap.off=\"none\" supplies the effort so the gateway receives reasoning_effort:\"none\" and does NOT enter runaway reasoning mode.",
	"thinkingLevelMap { off: \"none\" } (issue #16): NaN docs state that with no reasoning_effort parameter gemma4 defaults to reasoning ON (16,384-token budget), while `none`/`minimal` skip reasoning entirely (https://nan.builders/docs/models#controlling-reasoning, checked 2026-10-01). pi maps reasoning:\"off\" to reasoningEffort:undefined, so without this map `thinking: off` sent no parameter and the model reasoned anyway; the map sends reasoning_effort:\"none\" and actually disables reasoning.",
	"thinkingLevelMap { off: \"minimal\" } (issue #16, measured 2026-09-27 against live gateway, repro included in the issue): when pi maps reasoning:\"off\" to reasoningEffort:undefined, the thinkingLevelMap.off=\"minimal\" supplies the effort so the gateway receives reasoning_effort:\"minimal\" (38 reasoning tokens + answer). Note: \"none\" does NOT suppress reasoning on glm5.3-flash (13,382 tokens) — only \"minimal\" was measured to be effective. reasoning_effort_values includes \"minimal\" (not documented by NaN docs but accepted and effective by the gateway, issue #16).",
	"manual-only: \"mimo-v2.6-flash\" skipped: models.dev provider \"nan\" now lists it, so the manual-only entry is not emitted and the models.dev values are used (omnimodal model (text, image, audio input) served by NaN; limits and modalities from https://nan.builders/docs/models#mimo-v2-6-flash (checked 2026-09-25, quotas re-checked 2026-09-29): 1,048,576 context / 131,072 max output / 1.0B monthly quota per member. Reasoning: accepted, depth not adjustable (docs table, checked 2026-09-29). Tool calling: yes. Streaming: yes. Input modalities (pi-representable): text, image (audio not representable in pi's Model type). Fallback entry: emitted only while models.dev provider nan does not list the model — models.dev started listing it on 2026-09-29, so the generator then keeps the models.dev values and attaches this note to that entry instead of emitting a second one.)",
	"thinkingLevelMap { off: \"none\" } (issue #16): NaN docs state that with no reasoning_effort parameter every model uses its own default and that default is reasoning ON for qwen3.6 (16,384-token budget), while `none` and `minimal` skip the reasoning phase entirely (https://nan.builders/docs/models#controlling-reasoning, checked 2026-10-01). pi maps reasoning:\"off\" to reasoningEffort:undefined, so without this map `thinking: off` sent no parameter and the model reasoned anyway; the map sends reasoning_effort:\"none\" and actually disables reasoning.",
	"contextWindow 262,144: the earlier 1,000,000 override (maintainer-confirmed 2026-09-05) was withdrawn 2026-09-07 — the updated https://nan.builders/docs/models still states '262K token context, the model's native window' and models.dev agrees at 262,144; NaN docs are treated as the most reliable source (maintainer instruction, 2026-09-07)."
],
} as const;
