// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually — run `bun run generate-models` to update.
//
// Source: https://models.dev/api.json (provider "nan"), fetched 2026-09-04T19:27:42.137Z
// Provenance: every contextWindow/maxTokens/input/cost value traces to
// models.dev or to the per-entry notes below. Nothing is invented; entries
// models.dev documents incompletely are omitted and flagged instead.
//
// NaN serves these via LiteLLM behind an OpenAI-compatible API; pricing is
// membership-quota based, which models.dev reports as zero per-token cost.

import type { GeneratedModelEntry } from "../src/fetch-models.ts";

export const NAN_GENERATED_MODELS: readonly GeneratedModelEntry[] = [
	{
		"id": "deepseek-v4-flash",
		"name": "DeepSeek V4 Flash",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 1000000,
		"maxTokens": 384000,
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, supportsUsageInStreaming true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested.",
			"input includes image: NaN serves the Vision-Exp variant (confirmed at https://nan.builders/docs/models, 'takes images as input'); models.dev provider nan lists text only."
		],
		"extras": {
			"id": "deepseek-v4-flash",
			"name": "DeepSeek V4 Flash",
			"description": "Fast DeepSeek V4 lane for economical reasoning, coding, and long-context work",
			"family": "deepseek-flash",
			"attachment": false,
			"reasoning": true,
			"reasoning_options": [],
			"tool_call": true,
			"structured_output": true,
			"temperature": true,
			"knowledge": "2025-05",
			"release_date": "2026-04-24",
			"last_updated": "2026-04-24",
			"modalities": {
				"input": [
					"text"
				],
				"output": [
					"text"
				]
			},
			"open_weights": true,
			"limit": {
				"context": 1000000,
				"output": 384000
			},
			"cost": {
				"input": 0,
				"output": 0
			}
		}
	},
	{
		"id": "gemma4",
		"name": "Gemma 4 26B A4B IT",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 262144,
		"maxTokens": 32768,
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, supportsUsageInStreaming true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested."
		],
		"extras": {
			"id": "gemma4",
			"name": "Gemma 4 26B A4B IT",
			"description": "Open Gemma instruction model for efficient chat and self-hosted deployments",
			"family": "gemma",
			"attachment": true,
			"reasoning": true,
			"reasoning_options": [
				{
					"type": "toggle"
				}
			],
			"tool_call": true,
			"structured_output": true,
			"temperature": true,
			"release_date": "2026-04-02",
			"last_updated": "2026-04-02",
			"modalities": {
				"input": [
					"text",
					"image"
				],
				"output": [
					"text"
				]
			},
			"open_weights": true,
			"limit": {
				"context": 262144,
				"output": 32768
			},
			"cost": {
				"input": 0,
				"output": 0
			}
		}
	},
	{
		"id": "glm5.2",
		"name": "GLM-5.2",
		"reasoning": true,
		"input": [
			"text"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 500000,
		"maxTokens": 131072,
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, supportsUsageInStreaming true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested."
		],
		"extras": {
			"id": "glm5.2",
			"name": "GLM-5.2",
			"description": "Open flagship GLM for long-horizon coding agents, served at 500K context on the NaN premium tier",
			"family": "glm",
			"attachment": false,
			"reasoning": true,
			"reasoning_options": [],
			"tool_call": true,
			"structured_output": true,
			"temperature": true,
			"release_date": "2026-06-13",
			"last_updated": "2026-06-13",
			"modalities": {
				"input": [
					"text"
				],
				"output": [
					"text"
				]
			},
			"open_weights": true,
			"limit": {
				"context": 500000,
				"output": 131072
			},
			"cost": {
				"input": 0,
				"output": 0
			}
		}
	},
	{
		"id": "glm5.3-flash",
		"name": "GLM-5.3-Flash",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 1000000,
		"maxTokens": 131072,
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, supportsUsageInStreaming true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested."
		],
		"extras": {
			"id": "glm5.3-flash",
			"name": "GLM-5.3-Flash",
			"description": "Native multimodal GLM model for efficient coding and long-horizon agent tasks",
			"family": "glm",
			"attachment": true,
			"reasoning": true,
			"reasoning_options": [],
			"tool_call": true,
			"structured_output": true,
			"temperature": true,
			"release_date": "2026-08-26",
			"last_updated": "2026-08-26",
			"modalities": {
				"input": [
					"text",
					"image"
				],
				"output": [
					"text"
				]
			},
			"open_weights": false,
			"limit": {
				"context": 1000000,
				"output": 131072
			},
			"cost": {
				"input": 0,
				"output": 0
			}
		}
	},
	{
		"id": "mimo-v2.5",
		"name": "MiMo-V2.5",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 1048576,
		"maxTokens": 131072,
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, supportsUsageInStreaming true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested."
		],
		"extras": {
			"id": "mimo-v2.5",
			"name": "MiMo-V2.5",
			"description": "Open MiMo model for multimodal coding agents and long-context automation",
			"family": "mimo",
			"attachment": true,
			"reasoning": true,
			"reasoning_options": [],
			"tool_call": true,
			"temperature": true,
			"knowledge": "2024-12",
			"release_date": "2026-04-22",
			"last_updated": "2026-04-22",
			"modalities": {
				"input": [
					"text",
					"image",
					"audio"
				],
				"output": [
					"text"
				]
			},
			"open_weights": true,
			"limit": {
				"context": 1048576,
				"output": 131072
			},
			"cost": {
				"input": 0,
				"output": 0
			}
		}
	},
	{
		"id": "qwen3.6",
		"name": "Qwen3.6 35B-A3B",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 262144,
		"maxTokens": 65536,
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, supportsUsageInStreaming true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested."
		],
		"extras": {
			"id": "qwen3.6",
			"name": "Qwen3.6 35B-A3B",
			"description": "Open multimodal Qwen MoE for local agents that need vision, audio, and code",
			"family": "qwen",
			"attachment": true,
			"reasoning": true,
			"reasoning_options": [
				{
					"type": "toggle"
				}
			],
			"tool_call": true,
			"structured_output": true,
			"temperature": true,
			"release_date": "2026-04-17",
			"last_updated": "2026-04-17",
			"modalities": {
				"input": [
					"text",
					"image"
				],
				"output": [
					"text"
				]
			},
			"open_weights": true,
			"limit": {
				"context": 262144,
				"output": 65536
			},
			"cost": {
				"input": 0,
				"output": 0
			}
		}
	},
	{
		"id": "qwen3.8-flash",
		"name": "Qwen3.8 Flash",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 262144,
		"maxTokens": 131072,
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, supportsUsageInStreaming true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested."
		],
		"extras": {
			"id": "qwen3.8-flash",
			"name": "Qwen3.8 Flash",
			"description": "Qwen vision-language model for visual reasoning, documents, and agent tasks",
			"family": "qwen",
			"attachment": true,
			"reasoning": true,
			"reasoning_options": [],
			"tool_call": true,
			"structured_output": true,
			"release_date": "2026-08-26",
			"last_updated": "2026-08-26",
			"modalities": {
				"input": [
					"text",
					"image"
				],
				"output": [
					"text"
				]
			},
			"open_weights": false,
			"limit": {
				"context": 262144,
				"output": 131072
			},
			"cost": {
				"input": 0,
				"output": 0
			}
		}
	}
];

export const GENERATED_CATALOG_META = {
	source: "https://models.dev/api.json",
	modelsDevProvider: "nan",
	fetchedAt: "2026-09-04T19:27:42.137Z",
	modelCount: 7,
	models: ["deepseek-v4-flash","gemma4","glm5.2","glm5.3-flash","mimo-v2.5","qwen3.6","qwen3.8-flash"],
	notes: [
	"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, supportsUsageInStreaming true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested.",
	"input includes image: NaN serves the Vision-Exp variant (confirmed at https://nan.builders/docs/models, 'takes images as input'); models.dev provider nan lists text only."
],
} as const;
