// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually — run `bun run generate-models` to update.
//
// Source: https://models.dev/api.json (provider "nan"), fetched 2026-09-04T16:05:21.105Z
// Provenance: every contextWindow/maxTokens/input/cost value traces to
// models.dev or to the per-entry notes below. Nothing is invented; entries
// models.dev documents incompletely are omitted and flagged instead.
//
// NaN serves these via LiteLLM behind an OpenAI-compatible API; pricing is
// membership-quota based, which models.dev reports as zero per-token cost.

import type { GeneratedModelEntry } from "../src/fetch-models.ts";

export const NAN_GENERATED_MODELS: readonly GeneratedModelEntry[] = [
	{
		"id": "deepseek-v4-flash",
		"name": "DeepSeek V4 Flash",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 1000000,
		"maxTokens": 384000,
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, supportsUsageInStreaming true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested.",
			"input includes image: NaN serves the Vision-Exp variant (confirmed at https://nan.builders/docs/models, 'takes images as input'); models.dev provider nan lists text only."
		]
	},
	{
		"id": "gemma4",
		"name": "Gemma 4 26B A4B IT",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 262144,
		"maxTokens": 32768,
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, supportsUsageInStreaming true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested."
		]
	},
	{
		"id": "glm5.2",
		"name": "GLM-5.2",
		"reasoning": true,
		"input": [
			"text"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 500000,
		"maxTokens": 131072,
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, supportsUsageInStreaming true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested."
		]
	},
	{
		"id": "glm5.3-flash",
		"name": "GLM-5.3-Flash",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 1000000,
		"maxTokens": 131072,
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, supportsUsageInStreaming true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested."
		]
	},
	{
		"id": "mimo-v2.5",
		"name": "MiMo-V2.5",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 1048576,
		"maxTokens": 131072,
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, supportsUsageInStreaming true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested."
		]
	},
	{
		"id": "qwen3.6",
		"name": "Qwen3.6 35B-A3B",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 262144,
		"maxTokens": 65536,
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, supportsUsageInStreaming true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested."
		]
	},
	{
		"id": "qwen3.8-flash",
		"name": "Qwen3.8 Flash",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 262144,
		"maxTokens": 131072,
		"compat": {
			"supportsDeveloperRole": false,
			"supportsReasoningEffort": true,
			"supportsUsageInStreaming": true,
			"maxTokensField": "max_tokens"
		},
		"notes": [
			"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, supportsUsageInStreaming true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested."
		]
	}
];

export const GENERATED_CATALOG_META = {
	source: "https://models.dev/api.json",
	modelsDevProvider: "nan",
	fetchedAt: "2026-09-04T16:05:21.105Z",
	modelCount: 7,
	models: ["deepseek-v4-flash","gemma4","glm5.2","glm5.3-flash","mimo-v2.5","qwen3.6","qwen3.8-flash"],
	notes: [
	"compat matches the maintainer's working ~/.pi/agent/models.json LiteLLM config for api.nan.builders (2026-09-04): supportsDeveloperRole false, supportsReasoningEffort true, supportsUsageInStreaming true, maxTokensField max_tokens. NaN's docs example sets only supportsDeveloperRole: true and is not battle-tested.",
	"input includes image: NaN serves the Vision-Exp variant (confirmed at https://nan.builders/docs/models, 'takes images as input'); models.dev provider nan lists text only."
],
} as const;
